### ISSUE TITLE
Unable to get Drones to work levers correctly

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#558]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.30
### Mod Version
1.4.0-53
### Describe your problem, including steps to reproduce it

I'm trying to build a smart Plastic factory that turns off the vortex tubes when not needed. To accomplish this, I figured I'd toss the logic into a drone and let it turn them on and off by clicking a lever. 

The drones do go over to the lever, but sit there flicking it on and off in a loop instead. 

To double check that it wasn't some bad logic in my program, I put together a short program that just right clicks a lever and then should suicide. It never actually suicides. It just gets stuck in the same lever spam loop. 

### Any other comments?

Test Program: https://gist.github.com/MuteTiefling/abc1c2c55eac39ed714dbc80e37b1a5c

Also, congrats on your 1.16 release. You really cranked that thing out! 🥇

**Comment by desht** [comment]
This should be fixed in build 59.  It's down to changed behaviour from 1.12.2, where the action result of a block click could be FAIL, SUCCESS or PASS.  Newer versions of Minecraft also have CONSUME as a result, which needed to be treated as a SUCCESS.

(There were a couple of other problems too, but that was the main one)

**Comment by MuteTiefling** [comment]
Well, it doesn't spam click anymore, but it's still getting stuck.

Now it just goes over to the lever and hovers there. It never flicks it, nor does it do the suicide action following the right click action.

**Comment by desht** [comment]
Can I just confirm you have the progwidget set to "click block" rather than "click item" ?

**Comment by MuteTiefling** [comment]
Lol, woops. Derped hard on that one. Yeah, it's working fine when I switch it to Click Block.

**Comment by desht** [comment]
Fixed in 1.4.3 release
