### ISSUE TITLE
Failed to load datapacks

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#666]
### Minecraft Version
1.16.4

### Forge Version
35.1.0 and 35.1.7

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.7.0-83

### Describe your problem, including steps to reproduce it

Either starting a new world or loading an existing world causes this error.

Failed to load datapacks, can't proceed with server load

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: minecraft:fluid:forge:ethene,minecraft:fluid:forge:hydrogen

### Any other comments?
pneumaticcraft-repressurized-1.16.4-2.6.3-79 works just fine.

Creating a new instance and copying the mods over caused the same error.

Thanks for all you help.

**Comment by desht** [comment]
Ah, Mekanism fuel compat  :(  I'd hoped just adding the forge: fluid tags for those Mekanism tags would work OK, but apparently not without Mekanism actually present.

I'll do some conditional compat there, will be fixed in 2.7.1.

**Comment by desht** [comment]
Should be fixed in build 84 if you'd like to test...

**Comment by Alaberti** [comment]
> Should be fixed in build 84 if you'd like to test...

I'd be happy to test for you; where can I find the test build?

NVM FOUND IT

**Edit: I just wanted to take a moment to appreciate that this is issue 666 ^_^**

**Comment by Alaberti** [comment]
Okay! When tested by itself, works great! When tested with a bunch of other mods, also seems to have no issues! 

When tested with Quark 277 in any configuration, the issue persists, the world fails to load and the log balloons in size. 

Log: https://drive.google.com/file/d/1CDsDQUZNN10Iy7IiYBIkAvW55P1pnzWA/view?usp=sharing

**Comment by desht** [comment]
Yeah there's a recursive loop going on there during capability attaching. Not sure whose fault, but I could be doing something I shouldn't there - I'll take a look.

Short term workaround is to disable quark's shulker right click module.

**Comment by desht** [comment]
OK, build 85 should do the trick.  I added Quark to my test server and it all starts up and runs fine.

Update: released v2.7.2 with this hotfix.

**Comment by Alaberti** [comment]
Confirmed, works! Thank you!

**Comment by desht** [comment]
Excellent.

**Comment by duncanwebb** [comment]
Works for me too, many thanks for the quick fix/
